/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/shard1.glb --transform 
Files: src/assets/shard1.glb [5.21KB] > /home/melomimy/Development/DevHunt1/FyForce/fy-force-frontend/shard1-transformed.glb [1.63KB] (69%)
*/

import React, { useRef } from 'react'
import { useGLTF, MeshTransmissionMaterial } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shard1-transformed.glb')
  const meshRef = useRef(null)
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material}>
        <MeshTransmissionMaterial
          /* --- Configuration inspirée de votre image --- */
          
          // 1. Dispersion : L'effet "arc-en-ciel/prisme" indispensable
          // Augmentez cette valeur pour plus de couleurs séparées sur les bords.
          dispersion={1.0}
          reflectivity={0.3}
          metalness={0.1}

          // 2. Transparence et Réfraction
          transmission={1}         // 100% transparent
          ior={1.4}              // Indice de réfraction élevé (plus proche du cristal que du verre)
          
          // 3. Structure et Profondeur
          thickness={0.8}          // Donne du "poids" au verre
          roughness={0.0}          // Surface parfaitement lisse et brillante

          // 4. Teinte et Effets additionnels
          color="#ffffff"          // Garder blanc pour laisser la dispersion faire les couleurs
          chromaticAberration={0.1} // Légère aberration pour flouter les couleurs sur les bords
          anisotropy={0.3}         // Ajoute un peu de complexité aux reflets internes

          // 5. Paramètres techniques (pour la performance/qualité)
          resolution={1024}        // Résolution de la texture de réfraction
          samples={16}             // Qualité de l'échantillonnage (plus haut = plus beau mais plus lourd)
          backside={true}          // Rendre aussi l'intérieur du cristal pour plus de réalisme

          attenuationDistance={0.5}
          attenuationColor="#ffffff"
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/shard1-transformed.glb')
