/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/shard2.glb --transform 
Files: src/assets/shard2.glb [3.96KB] > /home/melomimy/Development/DevHunt1/FyForce/fy-force-frontend/shard2-transformed.glb [1.45KB] (63%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shard2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
    </group>
  )
}

useGLTF.preload('/shard2-transformed.glb')
